# ==============================================================================
# Merged Lakeflow Source: dati_gov_it
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from __future__ import annotations
from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import urllib.error
import urllib.parse
import urllib.request


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current start offset, or None on the first call.
                    PySpark's ``DataSourceStreamReader.latestOffset()`` does not
                    pass this yet, so the framework always sends None for now.
                    Connectors may use it to implement windowed batching when
                    called directly.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/dati_gov_it/dati_gov_it_schemas.py
    ########################################################

    DEFAULT_BASE_URL = "https://www.dati.gov.it/opendata/api/3/action"

    # CKAN's hard row cap per package_search call is 1000. We use that for
    # throughput — the portal doc suggests 100 as a "conservative" guideline but
    # there is no documented rate limit and CKAN accepts 1000.
    PAGE_SIZE = 1000

    # User-Agent identifies the connector to the upstream portal (dati.gov.it has
    # no documented rate limit but it is polite to identify ourselves).
    USER_AGENT = (
        "Mozilla/5.0 (compatible; lakeflow-community-connectors/0.1; "
        "+https://github.com/databrickslabs/lakeflow-community-connectors)"
    )

    # HTTP retry policy for transient 5xx / 429 responses.
    RETRIABLE_STATUS_CODES = {429, 500, 502, 503, 504}
    MAX_RETRIES = 3
    INITIAL_BACKOFF = 1.0  # seconds; doubled after each retry

    # Default size of a time window used for partitioned incremental reads of
    # packages/resources. 1 hour is a reasonable default — the portal's largest
    # days contain a few thousand modified packages, well within one page.
    DEFAULT_WINDOW_SECONDS = 24 * 60 * 60  # 24 hours
    MIN_WINDOW_SECONDS = 60

    # Hard floor for the incremental cursor when the connector has no prior
    # watermark and the user did not provide ``start_timestamp`` either.
    # dati.gov.it's oldest dataset is from 2014, so this is safe.
    DEFAULT_INCREMENTAL_FLOOR = "2014-01-01T00:00:00"

    # Supported tables (static — not dynamically discoverable).
    PACKAGES_TABLE = "packages"
    RESOURCES_TABLE = "resources"
    ORGANIZATIONS_TABLE = "organizations"
    TAGS_TABLE = "tags"
    GROUPS_TABLE = "groups"

    SUPPORTED_TABLES: list[str] = [
        PACKAGES_TABLE,
        RESOURCES_TABLE,
        ORGANIZATIONS_TABLE,
        TAGS_TABLE,
        GROUPS_TABLE,
    ]

    # Tables driven off package_search. Only these support incremental /
    # partitioned reads.
    INCREMENTAL_TABLES = {PACKAGES_TABLE, RESOURCES_TABLE}

    # Table-level connector filters that the user may set in ``external_options``.
    # These are only applied to packages / resources (which derives from packages).
    # Anything else is ignored.
    PACKAGE_FILTER_KEYS = ("organization", "tags", "groups", "res_format", "q")

    # ---------------------------------------------------------------------------
    # Nested struct schemas (shared between packages and resources)
    # ---------------------------------------------------------------------------

    # The ``extras`` payload is a free-form array of {key, value} pairs from the
    # DCAT-AP_IT profile. We intentionally keep values as raw strings because
    # upstream encodes structured content (lists, objects) as JSON within those
    # strings — downstream can parse on demand.
    EXTRAS_FIELD = StructField(
        "extras",
        ArrayType(
            StructType(
                [
                    StructField("key", StringType(), nullable=True),
                    StructField("value", StringType(), nullable=True),
                ]
            )
        ),
        nullable=True,
    )

    ORGANIZATION_NESTED_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=True),
            StructField("name", StringType(), nullable=True),
            StructField("title", StringType(), nullable=True),
            StructField("type", StringType(), nullable=True),
            StructField("description", StringType(), nullable=True),
            StructField("image_url", StringType(), nullable=True),
            StructField("created", TimestampType(), nullable=True),
            StructField("is_organization", BooleanType(), nullable=True),
            StructField("approval_status", StringType(), nullable=True),
            StructField("state", StringType(), nullable=True),
        ]
    )

    TAG_NESTED_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=True),
            StructField("name", StringType(), nullable=True),
            StructField("display_name", StringType(), nullable=True),
            StructField("state", StringType(), nullable=True),
            StructField("vocabulary_id", StringType(), nullable=True),
        ]
    )

    GROUP_NESTED_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=True),
            StructField("name", StringType(), nullable=True),
            StructField("title", StringType(), nullable=True),
            StructField("display_name", StringType(), nullable=True),
            StructField("description", StringType(), nullable=True),
            StructField("image_display_url", StringType(), nullable=True),
        ]
    )

    # Fields that live inside a single resource record. These are used both as
    # elements of ``packages.resources`` and — with ``package_id`` / parent
    # context added — as the row schema of the flat ``resources`` table.
    RESOURCE_FIELDS: list[StructField] = [
        StructField("id", StringType(), nullable=True),
        StructField("package_id", StringType(), nullable=True),
        StructField("name", StringType(), nullable=True),
        StructField("description", StringType(), nullable=True),
        StructField("url", StringType(), nullable=True),
        StructField("format", StringType(), nullable=True),
        StructField("distribution_format", StringType(), nullable=True),
        StructField("mimetype", StringType(), nullable=True),
        StructField("mimetype_inner", StringType(), nullable=True),
        StructField("size", IntegerType(), nullable=True),
        StructField("hash", StringType(), nullable=True),
        StructField("state", StringType(), nullable=True),
        StructField("position", IntegerType(), nullable=True),
        StructField("created", TimestampType(), nullable=True),
        StructField("last_modified", TimestampType(), nullable=True),
        StructField("metadata_modified", TimestampType(), nullable=True),
        StructField("url_type", StringType(), nullable=True),
        StructField("resource_type", StringType(), nullable=True),
        StructField("datastore_active", BooleanType(), nullable=True),
        StructField("cache_url", StringType(), nullable=True),
        StructField("cache_last_updated", StringType(), nullable=True),
        StructField("webstore_url", StringType(), nullable=True),
        StructField("webstore_last_updated", StringType(), nullable=True),
        StructField("license", StringType(), nullable=True),
        StructField("license_id", StringType(), nullable=True),
        StructField("license_type", StringType(), nullable=True),
        StructField("rights", StringType(), nullable=True),
        # Kept as string — the portal sometimes emits "DD-MM-YYYY" here.
        StructField("modified", StringType(), nullable=True),
        StructField("access_url", StringType(), nullable=True),
        StructField("uri", StringType(), nullable=True),
    ]

    RESOURCE_NESTED_SCHEMA = StructType(RESOURCE_FIELDS)

    # ---------------------------------------------------------------------------
    # Top-level table schemas
    # ---------------------------------------------------------------------------

    PACKAGES_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("name", StringType(), nullable=True),
            StructField("title", StringType(), nullable=True),
            StructField("notes", StringType(), nullable=True),
            StructField("type", StringType(), nullable=True),
            StructField("state", StringType(), nullable=True),
            StructField("private", BooleanType(), nullable=True),
            StructField("isopen", BooleanType(), nullable=True),
            StructField("license_id", StringType(), nullable=True),
            StructField("license_title", StringType(), nullable=True),
            StructField("license_url", StringType(), nullable=True),
            StructField("url", StringType(), nullable=True),
            StructField("version", StringType(), nullable=True),
            StructField("author", StringType(), nullable=True),
            StructField("author_email", StringType(), nullable=True),
            StructField("maintainer", StringType(), nullable=True),
            StructField("maintainer_email", StringType(), nullable=True),
            StructField("creator_user_id", StringType(), nullable=True),
            StructField("owner_org", StringType(), nullable=True),
            StructField("metadata_created", TimestampType(), nullable=True),
            StructField("metadata_modified", TimestampType(), nullable=True),
            StructField("num_resources", IntegerType(), nullable=True),
            StructField("num_tags", IntegerType(), nullable=True),
            StructField("holder_name", StringType(), nullable=True),
            StructField("holder_identifier", StringType(), nullable=True),
            StructField("dataset_is_local", BooleanType(), nullable=True),
            StructField("organization", ORGANIZATION_NESTED_SCHEMA, nullable=True),
            StructField("resources", ArrayType(RESOURCE_NESTED_SCHEMA), nullable=True),
            StructField("tags", ArrayType(TAG_NESTED_SCHEMA), nullable=True),
            StructField("groups", ArrayType(GROUP_NESTED_SCHEMA), nullable=True),
            EXTRAS_FIELD,
        ]
    )

    # Flat resources table. Each row is one element of a package's resources
    # array, with the parent ``package_metadata_modified`` watermark surfaced
    # as a top-level column so downstream can filter incrementally.
    RESOURCES_SCHEMA = StructType(
        RESOURCE_FIELDS
        + [
            StructField("package_metadata_modified", TimestampType(), nullable=True),
        ]
    )

    ORGANIZATIONS_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("name", StringType(), nullable=True),
            StructField("title", StringType(), nullable=True),
            StructField("display_name", StringType(), nullable=True),
            StructField("description", StringType(), nullable=True),
            StructField("image_url", StringType(), nullable=True),
            StructField("image_display_url", StringType(), nullable=True),
            StructField("created", TimestampType(), nullable=True),
            StructField("is_organization", BooleanType(), nullable=True),
            StructField("approval_status", StringType(), nullable=True),
            StructField("state", StringType(), nullable=True),
            StructField("type", StringType(), nullable=True),
            StructField("num_followers", IntegerType(), nullable=True),
            StructField("package_count", IntegerType(), nullable=True),
            StructField("identifier", StringType(), nullable=True),
            StructField("email", StringType(), nullable=True),
            StructField("site", StringType(), nullable=True),
            StructField("telephone", StringType(), nullable=True),
            EXTRAS_FIELD,
            StructField(
                "users",
                ArrayType(
                    StructType(
                        [
                            StructField("id", StringType(), nullable=True),
                            StructField("name", StringType(), nullable=True),
                            StructField("fullname", StringType(), nullable=True),
                            StructField("capacity", StringType(), nullable=True),
                            StructField("state", StringType(), nullable=True),
                            StructField("created", TimestampType(), nullable=True),
                            StructField("sysadmin", BooleanType(), nullable=True),
                        ]
                    )
                ),
                nullable=True,
            ),
        ]
    )

    TAGS_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("name", StringType(), nullable=True),
            StructField("display_name", StringType(), nullable=True),
            StructField("vocabulary_id", StringType(), nullable=True),
        ]
    )

    GROUPS_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("name", StringType(), nullable=True),
            StructField("title", StringType(), nullable=True),
            StructField("display_name", StringType(), nullable=True),
            StructField("description", StringType(), nullable=True),
            StructField("image_url", StringType(), nullable=True),
            StructField("image_display_url", StringType(), nullable=True),
            StructField("created", TimestampType(), nullable=True),
            StructField("is_organization", BooleanType(), nullable=True),
            StructField("approval_status", StringType(), nullable=True),
            StructField("state", StringType(), nullable=True),
            StructField("type", StringType(), nullable=True),
            StructField("num_followers", IntegerType(), nullable=True),
            StructField("package_count", IntegerType(), nullable=True),
            EXTRAS_FIELD,
        ]
    )

    TABLE_SCHEMAS: dict[str, StructType] = {
        PACKAGES_TABLE: PACKAGES_SCHEMA,
        RESOURCES_TABLE: RESOURCES_SCHEMA,
        ORGANIZATIONS_TABLE: ORGANIZATIONS_SCHEMA,
        TAGS_TABLE: TAGS_SCHEMA,
        GROUPS_TABLE: GROUPS_SCHEMA,
    }

    # Metadata describing primary key / cursor / ingestion semantics.
    # packages + resources are ``cdc`` (soft-deletes via state=deleted; no
    # separate delete endpoint, so we do not claim cdc_with_deletes).
    TABLE_METADATA: dict[str, dict] = {
        PACKAGES_TABLE: {
            "primary_keys": ["id"],
            "cursor_field": "metadata_modified",
            "ingestion_type": "cdc",
        },
        RESOURCES_TABLE: {
            "primary_keys": ["id"],
            # Watermark surfaced from the parent package. A resource changes
            # (or gets soft-deleted) iff its parent package re-saves, so the
            # package-level watermark is the right cursor for incremental.
            "cursor_field": "package_metadata_modified",
            "ingestion_type": "cdc",
        },
        ORGANIZATIONS_TABLE: {
            "primary_keys": ["id"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        TAGS_TABLE: {
            "primary_keys": ["id"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        GROUPS_TABLE: {
            "primary_keys": ["id"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/dati_gov_it/examples/enrich_snapshots.py
    ########################################################

    CATALOG = "users"
    SCHEMA = "federico_rizzo"
    BASE_URL = "https://www.dati.gov.it/opendata/api/3/action"
    ROWS = 1000          # page size (CKAN hard cap)

    # COMMAND ----------

    # MAGIC %md
    # MAGIC ## CKAN client (urllib, Mozilla-ish UA)

    # COMMAND ----------

    import urllib.request
    import urllib.parse
    import urllib.error
    import json
    import time

    UA = (
        "Mozilla/5.0 (compatible; dati-gov-it-enrich/0.1; "
        "+https://github.com/databrickslabs/lakeflow-community-connectors)"
    )


    def ckan_get(action: str, params: dict) -> dict:
        query = urllib.parse.urlencode(params, doseq=False)
        url = f"{BASE_URL}/{action}?{query}"
        for attempt in range(5):
            try:
                req = urllib.request.Request(url, method="GET")
                req.add_header("Accept", "application/json")
                req.add_header("User-Agent", UA)
                with urllib.request.urlopen(req, timeout=60) as resp:
                    body = json.loads(resp.read().decode("utf-8"))
                if not body.get("success"):
                    raise RuntimeError(f"CKAN {action} error: {body.get('error')}")
                return body["result"]
            except urllib.error.HTTPError as exc:
                if exc.code in (429, 500, 502, 503, 504) and attempt < 4:
                    time.sleep(2 ** attempt)
                    continue
                raise
        raise RuntimeError(f"Exhausted retries for {url}")


    # COMMAND ----------

    # MAGIC %md
    # MAGIC ## Page through `package_search` and dedupe by id

    # COMMAND ----------

    orgs_by_id: dict[str, dict] = {}
    groups_by_id: dict[str, dict] = {}
    tags_by_id: dict[str, dict] = {}

    start = 0
    total = None
    while True:
        page = ckan_get("package_search", {"q": "*:*", "rows": ROWS, "start": start})
        results = page.get("results") or []
        if not results:
            break

        for pkg in results:
            org = pkg.get("organization")
            if isinstance(org, dict) and org.get("id"):
                orgs_by_id.setdefault(org["id"], org)

            for g in (pkg.get("groups") or []):
                if isinstance(g, dict) and g.get("id"):
                    groups_by_id.setdefault(g["id"], g)

            for t in (pkg.get("tags") or []):
                if isinstance(t, dict) and t.get("id"):
                    tags_by_id.setdefault(t["id"], t)

        start += len(results)
        total = page.get("count", total or 0)
        print(
            f"scanned={start}/{total}  "
            f"orgs={len(orgs_by_id)}  groups={len(groups_by_id)}  tags={len(tags_by_id)}"
        )
        if len(results) < ROWS or start >= (total or 0):
            break

    print(
        f"\nDONE: {len(orgs_by_id)} organizations, "
        f"{len(groups_by_id)} groups, {len(tags_by_id)} tags"
    )

    # COMMAND ----------

    # MAGIC %md
    # MAGIC ## Write enriched tables

    # COMMAND ----------

    from pyspark.sql import functions as F


    def project(rows: list[dict], cols: list[str]) -> list[dict]:
        return [{c: r.get(c) for c in cols} for r in rows]


    org_cols = [
        "id", "name", "title", "description", "image_url",
        "created", "is_organization", "approval_status", "state", "type",
        "num_followers", "package_count",
    ]

    group_cols = [
        "id", "name", "title", "description", "image_display_url",
        "is_organization", "state", "type", "package_count",
    ]

    tag_cols = ["id", "name", "display_name", "vocabulary_id"]

    orgs_df = spark.createDataFrame(project(list(orgs_by_id.values()), org_cols))
    groups_df = spark.createDataFrame(project(list(groups_by_id.values()), group_cols))
    tags_df = spark.createDataFrame(project(list(tags_by_id.values()), tag_cols))

    # ISO 8601 → timestamp for the orgs.created column.
    orgs_df = orgs_df.withColumn("created", F.to_timestamp("created"))

    orgs_target = f"{CATALOG}.{SCHEMA}.organizations_enriched"
    groups_target = f"{CATALOG}.{SCHEMA}.groups_enriched"
    tags_target = f"{CATALOG}.{SCHEMA}.tags_enriched"

    orgs_df.write.mode("overwrite").option("overwriteSchema", "true").saveAsTable(orgs_target)
    print(f"  wrote {orgs_df.count():>6} rows → {orgs_target}")

    groups_df.write.mode("overwrite").option("overwriteSchema", "true").saveAsTable(groups_target)
    print(f"  wrote {groups_df.count():>6} rows → {groups_target}")

    tags_df.write.mode("overwrite").option("overwriteSchema", "true").saveAsTable(tags_target)
    print(f"  wrote {tags_df.count():>6} rows → {tags_target}")

    # COMMAND ----------

    # MAGIC %md
    # MAGIC ## Optional: create views that fill null columns on the pipeline tables

    # COMMAND ----------

    # These views LEFT JOIN the enriched tables onto the pipeline snapshots,
    # using COALESCE so any column that is null in the snapshot falls back to
    # the enriched value. Recreate these once — the pipeline only updates the
    # snapshot rows, not these views.

    spark.sql(f"""
    CREATE OR REPLACE VIEW {CATALOG}.{SCHEMA}.organizations_full AS
    SELECT
      s.id,
      COALESCE(s.name, e.name) AS name,
      COALESCE(e.title, s.title) AS title,
      COALESCE(e.description, s.description) AS description,
      COALESCE(e.image_url, s.image_url) AS image_url,
      COALESCE(e.created, s.created) AS created,
      COALESCE(e.is_organization, s.is_organization) AS is_organization,
      COALESCE(e.approval_status, s.approval_status) AS approval_status,
      COALESCE(e.state, s.state) AS state,
      COALESCE(e.type, s.type) AS type,
      COALESCE(e.num_followers, s.num_followers) AS num_followers,
      COALESCE(e.package_count, s.package_count) AS package_count
    FROM {CATALOG}.{SCHEMA}.organizations s
    LEFT JOIN {CATALOG}.{SCHEMA}.organizations_enriched e USING (id)
    """)

    spark.sql(f"""
    CREATE OR REPLACE VIEW {CATALOG}.{SCHEMA}.groups_full AS
    SELECT
      s.id,
      COALESCE(s.name, e.name) AS name,
      COALESCE(e.title, s.title) AS title,
      COALESCE(e.description, s.description) AS description,
      COALESCE(e.image_display_url, s.image_display_url) AS image_display_url,
      COALESCE(e.is_organization, s.is_organization) AS is_organization,
      COALESCE(e.state, s.state) AS state,
      COALESCE(e.type, s.type) AS type,
      COALESCE(e.package_count, s.package_count) AS package_count
    FROM {CATALOG}.{SCHEMA}.groups s
    LEFT JOIN {CATALOG}.{SCHEMA}.groups_enriched e USING (id)
    """)

    spark.sql(f"""
    CREATE OR REPLACE VIEW {CATALOG}.{SCHEMA}.tags_full AS
    SELECT
      COALESCE(e.id, s.id) AS id,
      COALESCE(s.name, e.name) AS name,
      COALESCE(e.display_name, s.display_name) AS display_name,
      COALESCE(e.vocabulary_id, s.vocabulary_id) AS vocabulary_id
    FROM {CATALOG}.{SCHEMA}.tags s
    LEFT JOIN {CATALOG}.{SCHEMA}.tags_enriched e ON s.name = e.name
    """)

    print("views created:")
    print(f"  {CATALOG}.{SCHEMA}.organizations_full")
    print(f"  {CATALOG}.{SCHEMA}.groups_full")
    print(f"  {CATALOG}.{SCHEMA}.tags_full")

    # COMMAND ----------

    # MAGIC %md
    # MAGIC ## Quick sanity check

    # COMMAND ----------

    display(spark.table(orgs_target).orderBy(F.desc("package_count")).limit(10))

    # COMMAND ----------

    display(spark.table(groups_target).orderBy(F.desc("package_count")).limit(20))

    # COMMAND ----------

    display(spark.table(tags_target).limit(10))


    ########################################################
    # src/databricks/labs/community_connector/sources/dati_gov_it/dati_gov_it.py
    ########################################################

    class _CKANClient:
        """Thin urllib-based client for the CKAN Action API.

        Designed to be cheap to construct on executors. ``read_partition`` builds
        a fresh client inside Spark workers so it must not rely on any shared
        mutable state from the driver.
        """

        def __init__(self, base_url: str, api_key: str | None = None, timeout: int = 60):
            self._base_url = base_url.rstrip("/")
            self._api_key = api_key or None
            self._timeout = timeout

        def get(self, action: str, params: dict[str, Any] | None = None) -> dict:
            """GET an action endpoint and return the unwrapped CKAN ``result``.

            Raises ``RuntimeError`` on HTTP errors (after retries) or when CKAN
            signals ``success: false`` in the response envelope.
            """
            query = urllib.parse.urlencode(_normalise_params(params or {}), doseq=False)
            url = f"{self._base_url}/{action}"
            if query:
                url = f"{url}?{query}"

            body = self._request(url)
            if not isinstance(body, dict) or not body.get("success", False):
                err = body.get("error") if isinstance(body, dict) else body
                raise RuntimeError(f"CKAN {action} returned error: {err}")
            return body["result"]

        def _request(self, url: str) -> dict:
            backoff = INITIAL_BACKOFF
            last_exc: Exception | None = None
            for attempt in range(MAX_RETRIES):
                try:
                    req = urllib.request.Request(url, method="GET")
                    req.add_header("Accept", "application/json")
                    req.add_header("User-Agent", USER_AGENT)
                    if self._api_key:
                        req.add_header("Authorization", self._api_key)
                    with urllib.request.urlopen(req, timeout=self._timeout) as resp:
                        raw = resp.read().decode("utf-8")
                    return json.loads(raw)
                except urllib.error.HTTPError as exc:
                    last_exc = exc
                    if exc.code not in RETRIABLE_STATUS_CODES or attempt == MAX_RETRIES - 1:
                        # Surface the body for easier debugging.
                        try:
                            detail = exc.read().decode("utf-8", errors="replace")[:500]
                        except Exception:
                            detail = ""
                        raise RuntimeError(
                            f"HTTP {exc.code} calling {url}: {detail}"
                        ) from exc
                except urllib.error.URLError as exc:
                    last_exc = exc
                    if attempt == MAX_RETRIES - 1:
                        raise RuntimeError(f"Network error calling {url}: {exc}") from exc
                time.sleep(backoff)
                backoff *= 2

            # Defensive — loop should always return or raise.
            raise RuntimeError(f"Exhausted retries calling {url}: {last_exc}")


    def _normalise_params(params: dict[str, Any]) -> list[tuple[str, str]]:
        """Flatten params, dropping Nones and coercing booleans to CKAN's lowercase."""
        out: list[tuple[str, str]] = []
        for key, value in params.items():
            if value is None:
                continue
            if isinstance(value, bool):
                out.append((key, "true" if value else "false"))
            else:
                out.append((key, str(value)))
        return out


    # ---------------------------------------------------------------------------
    # Connector
    # ---------------------------------------------------------------------------


    class DatiGovItLakeflowConnect(LakeflowConnect, SupportsPartitionedStream):
        """LakeflowConnect implementation for dati.gov.it.

        Extends :class:`SupportsPartitionedStream` so that packages and resources
        (the two high-volume tables) can be read in parallel across Spark
        executors using ``metadata_modified`` time windows. Other tables fall
        back to single-driver snapshot reads via ``read_table``.
        """

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            base_url = (options.get("base_url") or "").strip().rstrip("/")
            self._base_url = base_url or DEFAULT_BASE_URL
            self._api_key = options.get("api_key") or None

            # Driver-side client — only used from ``list_tables`` / ``read_table`` /
            # ``latest_offset``. Executors build their own client inside
            # ``read_partition`` so we never try to serialise this one.
            self._client = _CKANClient(self._base_url, self._api_key)

            # Freeze the "now" ceiling at init time so a single trigger never
            # chases new data forever. The next trigger gets a fresh instance
            # and therefore a fresh ceiling.
            self._init_ts = _utc_now_iso()

        # ------------------------------------------------------------------
        # LakeflowConnect surface
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            """Return the static list of supported tables (object list is hardcoded)."""
            return list(SUPPORTED_TABLES)

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            self._validate_table(table_name)
            # Copy so the caller cannot mutate our module-level dict.
            return dict(TABLE_METADATA[table_name])

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Single-driver read path.

            For snapshot tables this reads the full list. For packages/resources
            this is the fallback when partitioning is disabled — it performs a
            sequential sliding-window read advancing one window per call.
            """
            self._validate_table(table_name)
            table_options = table_options or {}

            if table_name == ORGANIZATIONS_TABLE:
                return self._read_organizations(table_options)
            if table_name == TAGS_TABLE:
                return self._read_tags(table_options)
            if table_name == GROUPS_TABLE:
                return self._read_groups(table_options)
            if table_name == PACKAGES_TABLE:
                return self._read_packages_window(start_offset, table_options)
            if table_name == RESOURCES_TABLE:
                return self._read_resources_window(start_offset, table_options)

            raise ValueError(f"Unhandled table: {table_name}")  # pragma: no cover

        # ------------------------------------------------------------------
        # SupportsPartitionedStream surface
        # ------------------------------------------------------------------

        def is_partitioned(self, table_name: str) -> bool:
            """Only packages and resources support partitioned reads.

            Organizations / tags / groups are small (~hundreds of rows at most),
            have no time-range filter on their list endpoints, and should use
            ``simpleStreamReader`` via ``read_table``.
            """
            return table_name in INCREMENTAL_TABLES

        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the current high-water mark for the streaming cursor.

            We use wall-clock "now at driver init" as the ceiling rather than a
            `package_search` metadata call. Packages are sorted by
            ``metadata_modified asc``, and any row with ``metadata_modified <=
            self._init_ts`` belongs in the batch. Using ``self._init_ts`` keeps
            the ceiling stable for the life of this driver instance so that
            micro-batches don't grow unboundedly.
            """
            self._validate_table(table_name)
            if table_name not in INCREMENTAL_TABLES:
                # Non-partitioned tables never call latest_offset in practice,
                # but return a stable empty dict to be defensive.
                return {}
            return {"cursor": self._init_ts}

        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Split the [start_cursor, end_cursor] range into time windows.

            Each returned descriptor is ``{"since": iso, "until": iso}`` and is
            fed to ``read_partition`` on an executor. The bounds are inclusive
            of ``since`` and exclusive of ``until`` — we add a negligible 1ms
            nudge on the seam to avoid duplicate fetches on back-to-back windows
            (Solr's range query is inclusive on both ends; we dedupe by letting
            the cursor advance monotonically, and rely on upsert semantics for
            the rare edge-on-seam record).
            """
            self._validate_table(table_name)
            table_options = table_options or {}

            if table_name not in INCREMENTAL_TABLES:
                # Single descriptor → whole table. This path is only exercised
                # if the framework calls ``get_partitions`` for a non-partitioned
                # table; ``is_partitioned`` returns False for these so normally
                # it doesn't happen.
                return [{"mode": "full"}]

            start = (start_offset or {}).get("cursor") if start_offset else None
            end = (end_offset or {}).get("cursor") if end_offset else None

            # When called from batch mode, start/end are None → cover everything
            # from the configured floor up to the init timestamp.
            if start is None:
                start = table_options.get("start_timestamp") or DEFAULT_INCREMENTAL_FLOOR
            if end is None:
                end = self._init_ts

            # Empty range — nothing to do. (Spark streaming sends start==end when
            # caught up.)
            if start >= end:
                return []

            window_seconds = max(
                int(table_options.get("window_seconds", DEFAULT_WINDOW_SECONDS)),
                MIN_WINDOW_SECONDS,
            )

            partitions: list[dict] = []
            cursor_dt = _parse_iso(start)
            end_dt = _parse_iso(end)
            while cursor_dt < end_dt:
                next_dt = min(cursor_dt + timedelta(seconds=window_seconds), end_dt)
                partitions.append(
                    {
                        "since": _to_iso(cursor_dt),
                        "until": _to_iso(next_dt),
                    }
                )
                cursor_dt = next_dt
            return partitions

        def read_partition(
            self,
            table_name: str,
            partition: dict,
            table_options: dict[str, str],
        ) -> Iterator[dict]:
            """Read one partition on a Spark executor.

            Re-creates a CKAN client from ``self.options`` so the call is
            self-contained — driver-side state (``self._client``, ``self._init_ts``)
            must not be relied upon here.
            """
            self._validate_table(table_name)
            table_options = table_options or {}

            # Full-table fallback — only happens if a caller invokes
            # ``get_partitions`` on a non-partitioned table.
            if partition.get("mode") == "full":
                if table_name == ORGANIZATIONS_TABLE:
                    records, _ = self._read_organizations(table_options)
                    return records
                if table_name == TAGS_TABLE:
                    records, _ = self._read_tags(table_options)
                    return records
                if table_name == GROUPS_TABLE:
                    records, _ = self._read_groups(table_options)
                    return records

            since = partition["since"]
            until = partition["until"]

            client = _CKANClient(self._base_url, self._api_key)
            if table_name == PACKAGES_TABLE:
                return iter(
                    self._paginate_packages_range(client, since, until, table_options)
                )
            if table_name == RESOURCES_TABLE:
                return iter(
                    self._paginate_resources_range(client, since, until, table_options)
                )
            raise ValueError(f"Unhandled partition for table: {table_name}")

        # ------------------------------------------------------------------
        # Snapshot table readers
        # ------------------------------------------------------------------

        def _read_organizations(
            self, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Enumerate organizations, sidestepping the WAF block on ``organization_list``.

            ``organization_list`` returns HTTP 403 from Databricks egress IPs
            regardless of parameters. ``package_search`` is not blocked and its
            ``organization`` facet exposes every org slug that has at least one
            dataset — which on this portal is every org. We pass ``rows=0`` +
            ``facet.limit=-1`` to fetch all facet buckets in a single call,
            then enrich each slug with ``organization_show``. When that call is
            also WAF-blocked for a given slug, fall back to a minimal record
            built from the facet count (with the slug as id, since id is
            non-nullable in ORGANIZATIONS_SCHEMA).
            """
            facets = self._client.get(
                "package_search",
                params={
                    "rows": 0,
                    "facet.field": '["organization"]',
                    "facet.limit": -1,
                },
            )
            orgs_facet = ((facets or {}).get("facets") or {}).get("organization") or {}
            slugs = list(orgs_facet.keys())

            records: list[dict] = []
            for slug in slugs:
                try:
                    rec = self._client.get(
                        "organization_show",
                        params={
                            "id": slug,
                            "include_datasets": False,
                            "include_dataset_count": True,
                            "include_extras": True,
                            "include_users": False,  # Per spec: don't fetch users.
                        },
                    )
                    records.append(_shape_organization(rec))
                except RuntimeError:
                    # organization_show is WAF-blocked on this instance. Fall
                    # back to the organization struct embedded in package_search
                    # results — it carries approval_status, created, description,
                    # image_url, state, title, type, is_organization (but not
                    # email/telephone/num_followers/identifier/site/users, which
                    # only /organization_show exposes).
                    records.append(
                        _shape_organization(
                            self._fetch_embedded_org(slug, orgs_facet.get(slug))
                        )
                    )
            return iter(records), {}

        def _fetch_embedded_org(self, slug: str, package_count: int | None) -> dict:
            try:
                result = self._client.get(
                    "package_search",
                    params={"q": f"organization:{slug}", "rows": 1, "facet": False},
                )
                pkgs = (result or {}).get("results") or []
                embedded = (pkgs[0].get("organization") if pkgs else None) or {}
            except RuntimeError:
                embedded = {}

            shaped = dict(embedded)
            # Fill in non-nullable id with the slug if we couldn't get the real UUID.
            shaped.setdefault("id", slug)
            shaped.setdefault("name", slug)
            shaped.setdefault("title", slug)
            shaped.setdefault("display_name", shaped.get("title") or slug)
            shaped.setdefault("type", "organization")
            shaped.setdefault("state", "active")
            shaped.setdefault("is_organization", True)
            shaped["package_count"] = package_count
            shaped["extras"] = []
            return shaped

        def _read_tags(
            self, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Enumerate tags, sidestepping the WAF block on ``tag_list``.

            Same strategy as organizations/groups: derive the tag set from the
            ``tags`` facet on ``package_search`` (which is not WAF-blocked) and
            fall back to a minimal record (name == id, since id is non-nullable
            in TAGS_SCHEMA) because ``tag_show`` is also blocked from these
            egress IPs.
            """
            facets = self._client.get(
                "package_search",
                params={
                    "rows": 0,
                    "facet.field": '["tags"]',
                    "facet.limit": -1,
                },
            )
            tags_facet = ((facets or {}).get("facets") or {}).get("tags") or {}

            records = [
                {"id": name, "name": name, "display_name": name, "vocabulary_id": None}
                for name in tags_facet.keys()
            ]
            return iter(records), {}

        def _read_groups(
            self, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Enumerate groups, sidestepping the WAF block on ``group_list``.

            The dati.gov.it WAF returns HTTP 403 on ``group_list`` regardless of
            parameters, User-Agent, or retry attempts. ``package_search`` is not
            blocked, and its ``groups`` facet exposes every group slug used by
            at least one dataset — which on this portal is every group. We ask
            for ``rows=0`` (no package payloads) and ``facet.limit=-1`` (all
            facet buckets), then enrich each slug with ``group_show``. When
            ``group_show`` is also WAF-blocked for a given slug, we fall back
            to a minimal record built from the facet count.
            """
            facets = self._client.get(
                "package_search",
                params={
                    "rows": 0,
                    "facet.field": '["groups"]',
                    "facet.limit": -1,
                },
            )
            groups_facet = ((facets or {}).get("facets") or {}).get("groups") or {}
            slugs = list(groups_facet.keys())

            records: list[dict] = []
            for slug in slugs:
                try:
                    rec = self._client.get(
                        "group_show",
                        params={
                            "id": slug,
                            "include_datasets": False,
                            "include_dataset_count": True,
                            "include_extras": True,
                            "include_users": False,
                        },
                    )
                    records.append(_shape_group(rec))
                except RuntimeError:
                    # group_show is WAF-blocked on this instance. Fall back to
                    # the group struct embedded in package_search results — it
                    # carries description, display_name, image_display_url,
                    # title (but not created/num_followers/approval_status/type,
                    # which only /group_show exposes).
                    records.append(
                        _shape_group(
                            self._fetch_embedded_group(slug, groups_facet.get(slug))
                        )
                    )
            return iter(records), {}

        def _fetch_embedded_group(self, slug: str, package_count: int | None) -> dict:
            try:
                result = self._client.get(
                    "package_search",
                    params={"q": f"groups:{slug}", "rows": 1, "facet": False},
                )
                pkgs = (result or {}).get("results") or []
                groups = (pkgs[0].get("groups") if pkgs else None) or []
                embedded = next((g for g in groups if g.get("name") == slug), {})
            except RuntimeError:
                embedded = {}

            shaped = dict(embedded)
            shaped.setdefault("id", slug)
            shaped.setdefault("name", slug)
            shaped.setdefault("title", slug)
            shaped.setdefault("display_name", shaped.get("title") or slug)
            shaped.setdefault("type", "group")
            shaped.setdefault("state", "active")
            shaped.setdefault("is_organization", False)
            shaped["package_count"] = package_count
            shaped["extras"] = []
            return shaped

        # ------------------------------------------------------------------
        # Packages / resources — sequential (fallback) window reader
        # ------------------------------------------------------------------

        def _read_packages_window(
            self, start_offset: dict | None, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            since, until = self._next_window(start_offset, table_options)
            if since is None:
                return iter([]), start_offset or {}

            # Sequential batch path (used by read_table / unit tests) materializes
            # the generator so we can compute the end offset. Streaming path goes
            # through read_partition which keeps the generator lazy.
            records = list(
                self._paginate_packages_range(self._client, since, until, table_options)
            )
            end_offset = self._advance_offset(records, until, start_offset, "metadata_modified")
            return iter(records), end_offset

        def _read_resources_window(
            self, start_offset: dict | None, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            since, until = self._next_window(start_offset, table_options)
            if since is None:
                return iter([]), start_offset or {}

            records = list(
                self._paginate_resources_range(self._client, since, until, table_options)
            )
            end_offset = self._advance_offset(
                records, until, start_offset, "package_metadata_modified"
            )
            return iter(records), end_offset

        def _next_window(
            self, start_offset: dict | None, table_options: dict[str, str]
        ) -> tuple[str | None, str | None]:
            """Compute the [since, until] window for a single sequential call.

            ``since`` comes from the checkpoint (``cursor``), falling back to
            ``start_timestamp`` in options, then to the hardcoded floor. ``until``
            is ``min(since + window_seconds, self._init_ts)``. When we have
            already caught up (since >= init_ts) we return (None, None) to tell
            the caller to emit nothing.
            """
            since = None
            if start_offset:
                since = start_offset.get("cursor")
            if not since:
                since = table_options.get("start_timestamp")
            if not since:
                since = DEFAULT_INCREMENTAL_FLOOR

            if since >= self._init_ts:
                return None, None

            window_seconds = max(
                int(table_options.get("window_seconds", DEFAULT_WINDOW_SECONDS)),
                MIN_WINDOW_SECONDS,
            )
            until_dt = min(
                _parse_iso(since) + timedelta(seconds=window_seconds),
                _parse_iso(self._init_ts),
            )
            return since, _to_iso(until_dt)

        @staticmethod
        def _advance_offset(
            records: list[dict],
            window_until: str,
            start_offset: dict | None,
            cursor_field: str,
        ) -> dict:
            """Compute the ``end_offset`` after a sequential window call.

            If the window yielded records, advance to ``max(records[*].cursor)``.
            Otherwise advance to ``window_until`` so the next call moves forward
            rather than looping forever. When the advanced cursor equals the
            starting cursor, return the original offset unchanged to signal
            pagination is exhausted (this is how the framework detects EOF).
            """
            if records:
                # Records may have ``None`` for the cursor in pathological cases;
                # filter those out defensively.
                cursors = [
                    _iso_string(r.get(cursor_field))
                    for r in records
                    if r.get(cursor_field) is not None
                ]
                if cursors:
                    next_cursor = max(cursors)
                else:
                    next_cursor = window_until
            else:
                next_cursor = window_until

            end_offset = {"cursor": next_cursor}
            if start_offset and start_offset == end_offset:
                return start_offset
            return end_offset

        # ------------------------------------------------------------------
        # Packages / resources — paginated range fetchers
        # ------------------------------------------------------------------

        def _paginate_packages_range(
            self,
            client: _CKANClient,
            since: str,
            until: str,
            table_options: dict[str, str],
        ) -> Iterator[dict]:
            """Yield all packages whose ``metadata_modified`` is in [since, until].

            Generator — rows stream through to Spark without accumulating in
            memory. Required because a single 1-day window on this portal can
            contain thousands of packages with nested resources/tags/groups,
            which blew past the 1GB serverless Python worker limit in the
            previous list-based implementation.
            """
            for pkg in self._iter_package_search(client, since, until, table_options):
                yield _shape_package(pkg)

        def _paginate_resources_range(
            self,
            client: _CKANClient,
            since: str,
            until: str,
            table_options: dict[str, str],
        ) -> Iterator[dict]:
            """Yield all resources belonging to packages in the [since, until] window."""
            for pkg in self._iter_package_search(client, since, until, table_options):
                parent_watermark = pkg.get("metadata_modified")
                for res in pkg.get("resources") or []:
                    yield _shape_resource(res, pkg.get("id"), parent_watermark)

        def _iter_package_search(
            self,
            client: _CKANClient,
            since: str,
            until: str,
            table_options: dict[str, str],
        ) -> Iterator[dict]:
            """Iterate raw ``package_search`` results in a time window."""
            max_records = _positive_int(table_options.get("max_records_per_batch"))

            fq_parts = [
                f"metadata_modified:[{_solr_date(since)} TO {_solr_date(until)}]"
            ]
            fq_parts.extend(_build_package_filters(table_options))
            fq = " ".join(fq_parts)

            q = table_options.get("q") or "*:*"
            include_deleted = _as_bool(table_options.get("include_deleted", "false"))

            start = 0
            yielded = 0
            while True:
                params = {
                    "q": q,
                    "fq": fq,
                    "rows": PAGE_SIZE,
                    "start": start,
                    "sort": "metadata_modified asc",
                    "include_deleted": include_deleted,
                    "facet": False,
                }
                result = client.get("package_search", params=params)
                batch = result.get("results", []) if isinstance(result, dict) else []
                count = result.get("count", 0) if isinstance(result, dict) else 0

                if not batch:
                    return

                for item in batch:
                    yield item
                    yielded += 1
                    if max_records and yielded >= max_records:
                        return

                # Stop on the last page.
                if len(batch) < PAGE_SIZE:
                    return
                start += len(batch)
                if start >= count:
                    return

        # ------------------------------------------------------------------
        # Helpers
        # ------------------------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {SUPPORTED_TABLES}"
                )


    # ---------------------------------------------------------------------------
    # Module-level helpers
    # ---------------------------------------------------------------------------


    def _utc_now_iso() -> str:
        """Current UTC time as a naive ISO 8601 string (to match portal format)."""
        return datetime.now(timezone.utc).replace(tzinfo=None).isoformat(timespec="microseconds")


    def _parse_iso(value: str) -> datetime:
        """Parse a portal ISO 8601 string into a naive UTC datetime."""
        v = value
        # Be forgiving of optional trailing "Z" from upstream variants.
        if v.endswith("Z"):
            v = v[:-1]
        try:
            dt = datetime.fromisoformat(v)
        except ValueError:
            # Fall back to a date-only parse (rare — dati.gov.it always sends
            # full timestamps, but user-supplied start_timestamp might be a date).
            dt = datetime.strptime(v, "%Y-%m-%d")
        if dt.tzinfo is not None:
            dt = dt.astimezone(timezone.utc).replace(tzinfo=None)
        return dt


    def _to_iso(dt: datetime) -> str:
        """Serialize a naive UTC datetime to the portal's format (no tz suffix)."""
        if dt.tzinfo is not None:
            dt = dt.astimezone(timezone.utc).replace(tzinfo=None)
        return dt.isoformat(timespec="microseconds")


    def _solr_date(value: str) -> str:
        """Convert an ISO string to Solr-range-friendly UTC form.

        Solr accepts ``YYYY-MM-DDTHH:MM:SSZ`` inside a range query. We normalise
        to that form — the portal itself stores the values without ``Z`` but
        accepts the ``Z`` form in queries.
        """
        dt = _parse_iso(value)
        return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


    def _as_bool(value: Any) -> bool:
        if isinstance(value, bool):
            return value
        if value is None:
            return False
        return str(value).strip().lower() in {"true", "1", "yes", "y"}


    def _positive_int(value: Any) -> int | None:
        if value is None or value == "":
            return None
        try:
            i = int(value)
        except (TypeError, ValueError):
            return None
        return i if i > 0 else None


    def _iso_string(value: Any) -> str:
        """Coerce a value we plan to use as a cursor back to an ISO string."""
        if isinstance(value, str):
            return value
        if isinstance(value, datetime):
            return _to_iso(value)
        return str(value)


    def _build_package_filters(table_options: dict[str, str]) -> list[str]:
        """Build Solr ``fq`` clauses from the connector's table-level options.

        All filters are ANDed. ``tags`` and ``groups`` may be comma-separated
        lists; each value becomes its own clause (Solr ANDs them too, matching
        user expectation: "datasets tagged with BOTH A and B").
        """
        out: list[str] = []
        for key in PACKAGE_FILTER_KEYS:
            if key == "q":
                continue  # ``q`` is a free-text param, not an fq clause.
            raw = table_options.get(key)
            if not raw:
                continue
            values = [v.strip() for v in str(raw).split(",") if v.strip()]
            for val in values:
                if key == "organization":
                    out.append(f"organization:{_solr_escape(val)}")
                elif key == "tags":
                    out.append(f"tags:{_solr_escape(val)}")
                elif key == "groups":
                    out.append(f"groups:{_solr_escape(val)}")
                elif key == "res_format":
                    out.append(f"res_format:{_solr_escape(val)}")
        return out


    _SOLR_SPECIAL = set('+-&|!(){}[]^"~*?:\\/ ')


    def _solr_escape(value: str) -> str:
        """Minimal Solr special-character escape plus whitespace quoting.

        For slugs / tag names / format codes the portal uses (which are all
        lowercase ascii with hyphens / dots) this is usually a no-op, but we
        defensively quote if the value contains whitespace or Solr specials.
        """
        if any(ch in _SOLR_SPECIAL for ch in value):
            escaped = value.replace("\\", "\\\\").replace('"', '\\"')
            return f'"{escaped}"'
        return value


    # ---------------------------------------------------------------------------
    # Record shapers — project raw CKAN payloads onto our flat schemas.
    # ---------------------------------------------------------------------------


    _PACKAGE_TOP_LEVEL = [
        "id",
        "name",
        "title",
        "notes",
        "type",
        "state",
        "private",
        "isopen",
        "license_id",
        "license_title",
        "license_url",
        "url",
        "version",
        "author",
        "author_email",
        "maintainer",
        "maintainer_email",
        "creator_user_id",
        "owner_org",
        "metadata_created",
        "metadata_modified",
        "num_resources",
        "num_tags",
        "holder_name",
        "holder_identifier",
        "dataset_is_local",
    ]

    _RESOURCE_FIELDS_TO_COPY = [
        "id",
        "package_id",
        "name",
        "description",
        "url",
        "format",
        "distribution_format",
        "mimetype",
        "mimetype_inner",
        "size",
        "hash",
        "state",
        "position",
        "created",
        "last_modified",
        "metadata_modified",
        "url_type",
        "resource_type",
        "datastore_active",
        "cache_url",
        "cache_last_updated",
        "webstore_url",
        "webstore_last_updated",
        "license",
        "license_id",
        "license_type",
        "rights",
        "modified",
        "access_url",
        "uri",
    ]

    _ORG_NESTED_FIELDS = [
        "id",
        "name",
        "title",
        "type",
        "description",
        "image_url",
        "created",
        "is_organization",
        "approval_status",
        "state",
    ]


    def _shape_package(raw: dict) -> dict:
        """Project a raw package_search result onto PACKAGES_SCHEMA."""
        out: dict[str, Any] = {k: raw.get(k) for k in _PACKAGE_TOP_LEVEL}
        out["organization"] = _shape_organization_nested(raw.get("organization"))
        out["resources"] = [
            _shape_resource_nested(r) for r in (raw.get("resources") or [])
        ]
        out["tags"] = [_shape_tag_nested(t) for t in (raw.get("tags") or [])]
        out["groups"] = [_shape_group_nested(g) for g in (raw.get("groups") or [])]
        out["extras"] = _shape_extras(raw.get("extras"))
        return out


    def _shape_resource(raw: dict, parent_id: str | None, parent_watermark: Any) -> dict:
        """Project a nested resource onto the flat RESOURCES_SCHEMA."""
        out = _shape_resource_nested(raw)
        # ``package_id`` is sometimes missing from the nested form — fall back
        # to the parent package's id.
        if not out.get("package_id") and parent_id:
            out["package_id"] = parent_id
        out["package_metadata_modified"] = parent_watermark
        return out


    def _shape_resource_nested(raw: dict | None) -> dict:
        if not isinstance(raw, dict):
            return {f: None for f in _RESOURCE_FIELDS_TO_COPY}
        return {f: raw.get(f) for f in _RESOURCE_FIELDS_TO_COPY}


    def _shape_organization_nested(raw: dict | None) -> dict | None:
        if not isinstance(raw, dict):
            return None
        return {f: raw.get(f) for f in _ORG_NESTED_FIELDS}


    def _shape_tag_nested(raw: dict | None) -> dict:
        if not isinstance(raw, dict):
            return {}
        return {
            "id": raw.get("id"),
            "name": raw.get("name"),
            "display_name": raw.get("display_name"),
            "state": raw.get("state"),
            "vocabulary_id": raw.get("vocabulary_id"),
        }


    def _shape_group_nested(raw: dict | None) -> dict:
        if not isinstance(raw, dict):
            return {}
        return {
            "id": raw.get("id"),
            "name": raw.get("name"),
            "title": raw.get("title"),
            "display_name": raw.get("display_name"),
            "description": raw.get("description"),
            "image_display_url": raw.get("image_display_url"),
        }


    def _shape_extras(raw: Any) -> list[dict] | None:
        """Preserve extras as array<struct<key, value>>.

        Values may be JSON-encoded strings (e.g. ``theme`` is a JSON list) — we
        keep them as raw strings per the API doc's guidance.
        """
        if not isinstance(raw, list):
            return None
        out: list[dict] = []
        for entry in raw:
            if not isinstance(entry, dict):
                continue
            val = entry.get("value")
            if val is not None and not isinstance(val, str):
                # Normalise non-string values to JSON so the whole column is a
                # uniform string.
                try:
                    val = json.dumps(val, ensure_ascii=False)
                except (TypeError, ValueError):
                    val = str(val)
            out.append({"key": entry.get("key"), "value": val})
        return out


    def _shape_organization(raw: dict) -> dict:
        """Project an ``organization_show`` response onto ORGANIZATIONS_SCHEMA."""
        return {
            "id": raw.get("id"),
            "name": raw.get("name"),
            "title": raw.get("title"),
            "display_name": raw.get("display_name"),
            "description": raw.get("description"),
            "image_url": raw.get("image_url"),
            "image_display_url": raw.get("image_display_url"),
            "created": raw.get("created"),
            "is_organization": raw.get("is_organization"),
            "approval_status": raw.get("approval_status"),
            "state": raw.get("state"),
            "type": raw.get("type"),
            "num_followers": raw.get("num_followers"),
            "package_count": raw.get("package_count"),
            "identifier": raw.get("identifier"),
            "email": raw.get("email"),
            "site": raw.get("site"),
            "telephone": raw.get("telephone"),
            "extras": _shape_extras(raw.get("extras")),
            "users": [_shape_user(u) for u in (raw.get("users") or [])],
        }


    def _shape_group(raw: dict) -> dict:
        """Project a ``group_show`` response onto GROUPS_SCHEMA."""
        return {
            "id": raw.get("id"),
            "name": raw.get("name"),
            "title": raw.get("title"),
            "display_name": raw.get("display_name"),
            "description": raw.get("description"),
            "image_url": raw.get("image_url"),
            "image_display_url": raw.get("image_display_url"),
            "created": raw.get("created"),
            "is_organization": raw.get("is_organization"),
            "approval_status": raw.get("approval_status"),
            "state": raw.get("state"),
            "type": raw.get("type"),
            "num_followers": raw.get("num_followers"),
            "package_count": raw.get("package_count"),
            "extras": _shape_extras(raw.get("extras")),
        }


    def _shape_user(raw: dict | None) -> dict:
        if not isinstance(raw, dict):
            return {}
        return {
            "id": raw.get("id"),
            "name": raw.get("name"),
            "fullname": raw.get("fullname"),
            "capacity": raw.get("capacity"),
            "state": raw.get("state"),
            "created": raw.get("created"),
            "sysadmin": raw.get("sysadmin"),
        }


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = DatiGovItLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowPartitionedStreamReader(DataSourceStreamReader):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def latestOffset(self):
            # PySpark does not pass the current offset to latestOffset() yet,
            # so we forward None.  Once PySpark supports it, pass the real value.
            return self.lakeflow_connect.latest_offset(self.table_name, self.table_options, None)

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name != METADATA_TABLE:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
